version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    depends_on:
      - mongodbtest
    environment:
      - NODE_ENV=production  # (Optional, for future use)
      - MONGO_URI=mongodb://mongodbtest:27017/seniorDesignTesting  # Ensures Flask connects to MongoDB in Docker
      - FLASK_ENV=development  # Enables debug mode (for hot-reloading)
      - FLASK_RUN_EXTRA_FILES=1  # Required for detecting changes
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Binds local code directory to container for live updates
    networks:
      - flask_network  # Ensures Flask can talk to MongoDB

  mongodbtest:
    image: mongo:6.0
    container_name: mongodbtest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistent storage
    networks:
      - flask_network  # Ensures Flask and MongoDB are on the same network

  # cloudflared:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   command: tunnel run dc9_1yHh9x2PConIVXWovSVOAnUUDS9ntYIFfQjS
  #   environment:
  #     - TUNNEL_TOKEN=dc9_1yHh9x2PConIVXWovSVOAnUUDS9ntYIFfQjS
  #   depends_on:
  #     - flask_app  # Ensures Flask is up before starting the tunnel

volumes:
  mongo-data:  # Persistent MongoDB storage

networks:
  flask_network:  # Custom network for Flask and MongoDB
    driver: bridge
