version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: my_mongo
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI = "mongodb://my_mongo:27017/"
    depends_on:
      - mongo
